os: linux
dist: xenial
language: java
jdk:
  - oraclejdk11

services:
  - docker

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - docker-compose --version

script:
  - ./gradlew check
  - ./gradlew integrationTest

deploy:
  - provider: releases
    token: ${GH_TOKEN}
    file_glob: true
    file:
      - "build/libs/*.war"
    cleanup: false
    on:
      tags: true
