language: java
jdk:
  - oraclejdk8
sudo: true

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.19.0
  - DOCKER_COMPOSE=/usr/local/bin/docker-compose
  - DOCKER_COMPOSE_FILE=src/integrationTest/docker/docker-compose.yml

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - sudo curl -L https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` -o $DOCKER_COMPOSE
  - sudo chmod +x $DOCKER_COMPOSE

script:
  - ./gradlew check
  - cd src/integrationTest/docker
  - sudo $DOCKER_COMPOSE -f $DOCKER_COMPOSE_FILE up -d && sleep 60
  - ./gradlew integrationTest
  - sudo $DOCKER_COMPOSE -f $DOCKER_COMPOSE_FILE down
  - cd ../../..

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file_glob: true
    file:
      - "build/libs/*.war"
    skip_cleanup: true
    on:
      tags: true
