language: java
jdk:
  - oraclejdk8
sudo: true

services:
  - docker

env:
  - DOCKER_COMPOSE_FILE=src/integrationTest/docker/docker-compose.yml

cache:
  directories:
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/jars-2
    - $HOME/.gradle/caches/jars-3
    - $HOME/.gradle/caches/modules-2/files-2.1/
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_install:
  - docker-compose --version

script:
  - ./gradlew check
  - cd src/integrationTest/docker
  - sudo docker-compose -f $DOCKER_COMPOSE_FILE up -d && sleep 60
  - ./gradlew integrationTest
  - sudo docker-compose -f $DOCKER_COMPOSE_FILE down
  - cd ../../..

deploy:
  - provider: releasesq
    api_key: ${GH_TOKEN}
    file_glob: true
    file:
      - "build/libs/*.war"
    skip_cleanup: true
    on:
      tags: true
