---
version: '2'

networks:
  zookeeper:
    driver: bridge
  kafka:
    driver: bridge
  identity:
    driver: bridge

services:
  #---------------------------------------------------------------------------#
  # Zookeeper Cluster                                                         #
  #---------------------------------------------------------------------------#
  zookeeper-1:
    image: confluentinc/cp-zookeeper:3.1.2-1
    networks:
      - zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888

  #---------------------------------------------------------------------------#
  # Kafka Cluster                                                             #
  #---------------------------------------------------------------------------#
  kafka-1:
    image: confluentinc/cp-kafka:3.1.2-1
    networks:
      - kafka
      - zookeeper
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  #---------------------------------------------------------------------------#
  # Schema Registry                                                           #
  #---------------------------------------------------------------------------#
  schema-registry-1:
    image: confluentinc/cp-schema-registry:3.1.2-1
    networks:
      - kafka
      - zookeeper
    depends_on:
      - kafka-1
    restart: always
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper-1:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-1
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry-1:8081

  #---------------------------------------------------------------------------#
  # REST proxy                                                                #
  #---------------------------------------------------------------------------#
  rest-proxy-1:
    image: confluentinc/cp-kafka-rest:3.1.2-1
    networks:
      - kafka
      - zookeeper
    depends_on:
      - kafka-1
      - schema-registry-1
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_REST_LISTENERS: http://rest-proxy-1:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry-1:8081
      KAFKA_REST_HOST_NAME: rest-proxy-1

  #---------------------------------------------------------------------------#
  # RADAR Gateway                                                            #
  #---------------------------------------------------------------------------#
  rest-gateway:
    build: ./
    image: radarcns/radar-gateway:latest
    networks:
      - kafka
      - zookeeper
      - identity
    ports:
      - "8080:8080"

  #---------------------------------------------------------------------------#
  # WSO2 Identity Server                                                      #
  #---------------------------------------------------------------------------#
  is:
    image: isim/wso2is:$IS_VERSION
    networks:
      - identity
    hostname: localhost
    ports:
    - "9443:9443"
    - "9763:9763"
    volumes:
    - ./wso2is/master-datasources.xml:/opt/wso2is-$IS_VERSION/repository/conf/datasources/master-datasources.xml
    - ./wso2is/carbon.xml:/opt/wso2is-$IS_VERSION/repository/conf/carbon.xml
    - ./wso2is/registry.xml:/opt/wso2is-$IS_VERSION/repository/conf/registry.xml
    - ./wso2is/user-mgt.xml:/opt/wso2is-$IS_VERSION/repository/conf/user-mgt.xml
    - ./wso2is/sso-idp-config.xml:/opt/wso2is-$IS_VERSION/repository/conf/security/sso-idp-config.xml
